admin:
  email: rascal@gmail.com
  password: atmin123

security:
  internal_signature: atlanta331

notification:
  email:
    username: "faiqemilzzz@gmail.com"
    password: "zxyl hefl gacd ytzm "
    from: "faiqemilzzz@gmail.com"
