services:
  auth:
    host: localhost
    port: 8081
  user:
    host: localhost
    port: 8082
  notification:
    host: localhost
    port: 8083
  course:
    host: localhost
    port: 8084

database:
  provider: postgresql
  host: localhost
  port: 5555
  username: rascal
  password: ""
  sslmode: disable
  names:
    auth_service: mcr_auth
    user_service: mcr_user
    course_service: mcr_course

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  prefixes: 
    session: "session:"
    ban: "banned:users"
  streams:
    user_events: "user:events"
    notification_emails: "notification:emails"

default_pagination:
  size: 10
  max_size: 100

auth:
  session_ttl_hours: 24
  activation_ttl_minutes: 30
  activation_url: "http://localhost:5173/activate"

notification:
  email:
    host: smtp.gmail.com
    port: 465
    auth: true
    starttls: false
    starttls_required: false
    ssl: true
    debug: false
    connection_timeout_ms: 10000
    timeout_ms: 10000
    write_timeout_ms: 10000
